Create Event Api
GDSC-ASU/website pull request #19
Opened 2024-03-02 19:00 UTC by RemasMehyar

2024-03-02 19:10 UTC, RemasMehyar commented on src/lib/utils/requests/EventRequests.ts
> +	altImagePath
send 1 Event param instead of sending 6 params

2024-03-02 19:10 UTC, RemasMehyar commented on src/lib/utils/requests/EventRequests.ts
> +		altImagePath
same here

2024-03-02 20:12 UTC, RemasMehyar commented on package.json
> -    }
test

2024-03-02 21:40 UTC, mbaraa requested changes
check the change request comments

2024-03-02 21:40 UTC, mbaraa commented on src/lib/data/gdsc.db
@RemasMehyar 
remove this file, and add it to .gitignore

2024-03-02 21:40 UTC, mbaraa commented on src/lib/data/gdscDB.ts
> +  storage: "$lib/data/gdsc.db",
@RemasMehyar 
remove this static path, instead utilize the environment variable `VITE_SQLITE_FILE_PATH`, and add the static path to `.env.example` file.

2024-03-02 21:40 UTC, mbaraa commented on src/lib/utils/requests/EventRequests.ts
> +	altImagePath
can you clarify even more?

2024-03-02 21:40 UTC, mbaraa commented on src/lib/utils/requests/EventRequests.ts
> +		altImagePath
same here

2024-03-05 11:01 UTC, mbaraa approved these changes
good job!

2024-03-05 11:01 UTC, merged