Implement project schema and api
GDSC-ASU/website pull request #22
Opened 2024-03-06 13:50 UTC by Dimah02

2024-03-06 15:09 UTC, mbaraa commented on src/lib/data/index.ts
>  import { Event } from "$lib/data/Event";
update this import path to `./Event`

2024-03-06 15:09 UTC, mbaraa commented on src/lib/utils/requests/ProjectRequests.ts
> +	public static async getAllProjects() {
reflect this renaming in `src/routes/+page.server.ts`

2024-03-06 15:09 UTC, mbaraa requested changes
update the changes as requested in the comments.

2024-03-11 11:59 UTC, Dimah02 commented
I updated the names of the functions in the components, but I couldn't resolve the issue on my local repo this still occurs when `npm run dev`

```
TypeError: Cannot read properties of undefined (reading 'define')
    at C:/Users/deema/Desktop/svelt/website/src/lib/data/Event.ts:4:32
```
and I noticed that the name of the database file in the data folder is gdsc.db but in the `.env.example`  is gdscasu.db, is that ok?

2024-03-11 21:14 UTC, mbaraa commented
> I updated the names of the functions in the components, but I couldn't resolve the issue on my local repo this still occurs when `npm run dev`
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'define')
>     at C:/Users/deema/Desktop/svelt/website/src/lib/data/Event.ts:4:32
> ```
> 
> and I noticed that the name of the database file in the data folder is gdsc.db but in the `.env.example` is gdscasu.db, is that ok?

looks like it's a TS import conflict issue, I'll merge your PR and I'll fix this in another PR.

2024-03-11 21:14 UTC, mbaraa approved these changes
LGTM

2024-03-11 21:15 UTC, merged